name: Update

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-slim
    concurrency: git-push-${{ github.ref }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v6

      - name: Checkout library branch
        uses: actions/checkout@v6
        with:
          ref: "library"
          path: "library"

      - name: Install htmlq
        run: |
          wget https://github.com/mgdm/htmlq/releases/download/v0.4.0/htmlq-x86_64-linux.tar.gz -O htmlq.tar.gz
          tar -xf htmlq.tar.gz

      - name: Update models
        run: |
          export PATH="$PWD:$PATH"
          ./update-models.bash

      - name: Commit changes
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git commit --message "Update ollama models"; then
              echo "committed=true" >>"$GITHUB_OUTPUT"
          else
              echo "committed=false" >>"$GITHUB_OUTPUT"
          fi
        working-directory: library/

      - name: Push changes
        if: steps.commit.outputs.committed == 'true'
        run: git push origin refs/heads/library
        working-directory: library/
